### ISSUE TITLE
Unfortunately, Torogo has stopped

### ISSUE THREAD

**Issue by laercioskt** [beothorn/Torogo#20]
erro esta ocorrendo tanto ao rodar em emulador com android 5.1.0 quanto no celular com android 5.0.2 

05-25 01:17:30.943    1932-1932/beothorn.github.com.toroidalgo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: beothorn.github.com.toroidalgo, PID: 1932
    java.lang.RuntimeException: Unable to start activity ComponentInfo{beothorn.github.com.toroidalgo/beothorn.github.com.toroidalgo.ToroidalGoActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
            at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1686)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1787)
            at android.app.ContextImpl.bindService(ContextImpl.java:1765)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
            at sneer.android.PartnerSession.<init>(PartnerSession.java:86)
            at sneer.android.PartnerSession.join(PartnerSession.java:30)
            at beothorn.github.com.toroidalgo.ToroidalGoActivity.onCreate(ToroidalGoActivity.java:30)

**Comment by beothorn** [comment]
Acho que é um bug do sneer.
linha 30

final PartnerSession session = PartnerSession.join(this, new PartnerSession.Listener() {

**Comment by laercioskt** [comment]
laucher estava abrindo a activity, mas ela só pode ser aberta por dentro do sneer

**Comment by felipebueno** [comment]
@laercioskt atualiza a sneer-api pra v0.1.6. :+1: 

 Ela lida com isso agora... se o cara abrir pelo launcher ela avisa pra rodar pelo sneer... avisa até se o sneer está instalado ou não.

**Comment by felipebueno** [comment]
opa esqueci q posso comitar aqui. Vou fazer isso :+1:
